local version = require("pub-version.version")

describe("version", function()
  describe("parse", function()
    it("parses basic semver", function()
      local v = version.parse("1.2.3")
      assert.are.equal(1, v.major)
      assert.are.equal(2, v.minor)
      assert.are.equal(3, v.patch)
      assert.is_nil(v.prerelease)
      assert.is_nil(v.build)
    end)

    it("parses version with build metadata", function()
      local v = version.parse("5.3.2+1")
      assert.are.equal(5, v.major)
      assert.are.equal(3, v.minor)
      assert.are.equal(2, v.patch)
      assert.is_nil(v.prerelease)
      assert.are.equal("1", v.build)
    end)

    it("parses version with prerelease", function()
      local v = version.parse("1.0.0-alpha.1")
      assert.are.equal(1, v.major)
      assert.are.equal(0, v.minor)
      assert.are.equal(0, v.patch)
      assert.are.equal("alpha.1", v.prerelease)
      assert.is_nil(v.build)
    end)

    it("parses version with prerelease and build", function()
      local v = version.parse("1.0.0-beta.2+build.123")
      assert.are.equal("beta.2", v.prerelease)
      assert.are.equal("build.123", v.build)
    end)

    it("parses prerelease with hyphens", function()
      local v = version.parse("1.0.0-rc-1")
      assert.are.equal("rc-1", v.prerelease)
    end)

    it("returns nil for invalid input", function()
      assert.is_nil(version.parse(nil))
      assert.is_nil(version.parse("abc"))
      assert.is_nil(version.parse("1.2"))
      assert.is_nil(version.parse(""))
    end)
  end)

  describe("compare", function()
    it("returns 0 for equal versions", function()
      assert.are.equal(0, version.compare("1.2.3", "1.2.3"))
    end)

    it("compares major versions", function()
      assert.are.equal(-1, version.compare("1.0.0", "2.0.0"))
      assert.are.equal(1, version.compare("3.0.0", "2.0.0"))
    end)

    it("compares minor versions", function()
      assert.are.equal(-1, version.compare("1.2.0", "1.3.0"))
      assert.are.equal(1, version.compare("1.5.0", "1.3.0"))
    end)

    it("compares patch versions", function()
      assert.are.equal(-1, version.compare("1.2.3", "1.2.4"))
      assert.are.equal(1, version.compare("1.2.5", "1.2.4"))
    end)

    it("prerelease is lower than release", function()
      assert.are.equal(-1, version.compare("1.0.0-alpha", "1.0.0"))
      assert.are.equal(1, version.compare("1.0.0", "1.0.0-alpha"))
    end)

    it("compares prerelease numeric identifiers as integers", function()
      -- semver: alpha.2 < alpha.10 (numeric comparison)
      assert.are.equal(-1, version.compare("1.0.0-alpha.2", "1.0.0-alpha.10"))
      assert.are.equal(1, version.compare("1.0.0-alpha.10", "1.0.0-alpha.2"))
    end)

    it("compares prerelease string identifiers lexicographically", function()
      assert.are.equal(-1, version.compare("1.0.0-alpha", "1.0.0-beta"))
      assert.are.equal(1, version.compare("1.0.0-beta", "1.0.0-alpha"))
    end)

    it("numeric prerelease ids sort before string ids", function()
      assert.are.equal(-1, version.compare("1.0.0-1", "1.0.0-alpha"))
      assert.are.equal(1, version.compare("1.0.0-alpha", "1.0.0-1"))
    end)

    it("fewer prerelease fields = lower precedence", function()
      assert.are.equal(-1, version.compare("1.0.0-alpha", "1.0.0-alpha.1"))
      assert.are.equal(1, version.compare("1.0.0-alpha.1", "1.0.0-alpha"))
    end)

    it("returns nil for unparseable versions", function()
      assert.is_nil(version.compare("abc", "1.0.0"))
      assert.is_nil(version.compare("1.0.0", "xyz"))
      assert.is_nil(version.compare("nope", "nah"))
    end)

    it("ignores build metadata in comparison", function()
      assert.are.equal(0, version.compare("1.0.0+build1", "1.0.0+build2"))
    end)
  end)

  describe("upgrade_type", function()
    it("detects major upgrades", function()
      assert.are.equal("major", version.upgrade_type("1.0.0", "2.0.0"))
      assert.are.equal("major", version.upgrade_type("5.3.2", "6.0.0"))
    end)

    it("detects minor upgrades", function()
      assert.are.equal("minor", version.upgrade_type("1.2.0", "1.3.0"))
      assert.are.equal("minor", version.upgrade_type("6.0.5", "6.1.5"))
    end)

    it("detects patch upgrades", function()
      assert.are.equal("patch", version.upgrade_type("1.2.3", "1.2.4"))
      assert.are.equal("patch", version.upgrade_type("8.1.3", "8.1.6"))
    end)

    it("detects prerelease upgrades", function()
      assert.are.equal("prerelease", version.upgrade_type("1.0.0-alpha", "1.0.0"))
      assert.are.equal("prerelease", version.upgrade_type("1.0.0-alpha.2", "1.0.0-alpha.10"))
    end)

    it("detects up-to-date", function()
      assert.are.equal("up_to_date", version.upgrade_type("1.0.0", "1.0.0"))
      assert.are.equal("up_to_date", version.upgrade_type("3.0.1", "3.0.1"))
    end)

    it("returns up_to_date when current is newer", function()
      assert.are.equal("up_to_date", version.upgrade_type("2.0.0", "1.0.0"))
      assert.are.equal("up_to_date", version.upgrade_type("1.0.0", "1.0.0-alpha"))
    end)

    it("returns unknown for unparseable versions", function()
      assert.are.equal("unknown", version.upgrade_type("abc", "1.0.0"))
      assert.are.equal("unknown", version.upgrade_type("1.0.0", "xyz"))
    end)

    it("handles build metadata correctly", function()
      assert.are.equal("up_to_date", version.upgrade_type("5.3.2+1", "5.3.2+2"))
      assert.are.equal("minor", version.upgrade_type("5.3.2+1", "5.4.0"))
    end)
  end)
end)
